# Generated by Django 3.1 on 2021-07-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('street', models.CharField(max_length=128)),
                ('house_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('quality', models.CharField(max_length=128)),
                ('catagory', models.CharField(max_length=128)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
