# Generated by Django 3.1 on 2021-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210710_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
