# Generated by Django 3.1 on 2021-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210701_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_status',
            field=models.BooleanField(default=False),
        ),
    ]
