# Generated by Django 3.1 on 2021-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210711_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to='product-images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
