# Generated by Django 3.2.3 on 2021-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210629_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='street',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='phone_2',
            new_name='whatsapp_no',
        ),
        migrations.RemoveField(
            model_name='location',
            name='house_no',
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
