# Generated by Django 3.2.3 on 2021-07-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210702_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='whatsapp_no',
            field=models.IntegerField(null=True),
        ),
    ]
