# Generated by Django 3.2.3 on 2021-07-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210701_1148'),
        ('mainApp', '0004_alter_seller_whatsapp_no'),
    ]

    operations = [
    ]
